title: "Front-End Developer & UI/UX Designer"
duration: "2016 – 2019 (3y 9m)"
location: "On-site"
company: "LABHacker"
info: "In Brazilian House of Representatives"
responsibilities:
  - "Led the product discovery, the Design Sprint facilitation, and implemented the user experience for the reboot of Wikilegis, innovating how Brazilian law drafts can receive citizen opinions, have them judged in a Tinder-like fashion, while also empowering law-makers through a custom legislative text editor and consensus analysis of each opinion that has been judged by citizens."
  - "Designed and implemented the user experience for Audiências Interativas, which enabled citizens to remotely have their questions crowd-ranked and answered in public hearings from the House of Representatives. Committees adopted the tool so much, that now around 55% of all hearings are available on it."
stack:
  - "ES6+"
  - "jQuery with Pub/Sub Pattern"
  - "SASS"
  - "RSCSS"
  - "ABCSS"
  - "Django"
  - "ES5"
design:
  - "Figma"
  - "Miro"