name: Deploy to Github Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v2
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

  conditional-pdf-generation:
    if: github.actor != 'github-actions[bot]'
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Generate PDF Workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"event_type": "generate-pdf"}' \
            https://api.github.com/repos/${{ github.repository }}/dispatches