name: Generate PDF and Commit

on:
  repository_dispatch:
    types: [generate-pdf]

jobs:
  generate-cv-pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Generate PDF from live site
        run: node src/scripts/generate-cv-pdf.js https://caio.viotti.me/cv "./public/Caio Viotti Resume 2024.pdf"
      - name: Commit PDF
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add "./public/Caio Viotti Resume 2024.pdf"
          git commit -m "Update CV PDF"
          git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/cfviotti/cfviotti.github.io.git HEAD:main